import {
  AppMenuIcon,
  BellIcon,
  CancelIcon,
  MenuIcon,
  SearchIcon,
  ShoppingBagIcon,
  UserCircleIcon,
  InboxIcon,
  ProfileIcon,
  SettingsIcon,
  BucketIcon,
  DollarCircleIcon,
  LogoutIcon,
  MessageDownloadIcon,
  UserAddIcon,
  HeartIcon,
  ChatBubbleIcon,
  VideoIcon,
  EyeIcon,
  ChevronRightIcon,
  CollectionIcon,
  FireIcon,
  SunIcon,
  MoonIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  ChevronLeftIcon,
  FilterIcon,
  PlusIcon,
  UploadIcon,
  DownloadIcon,
  TrashIcon,
  EditIcon,
  SortIcon,
  SortUpIcon,
  SortDownIcon,
  ChartBarIcon,
} from '../components/Icons';
import {
  ArrowLeftIcon,
  ArrowRightIcon,
  CheckIcon,
  Loader2,
  LayoutGrid,
} from 'lucide-react';

export const Icons = {
  search: SearchIcon,
  menu: MenuIcon,
  cancel: CancelIcon,
  bell: BellIcon,
  apps: AppMenuIcon,
  shoppingBag: ShoppingBagIcon,
  userCircle: UserCircleIcon,
  inbox: InboxIcon,
  profile: ProfileIcon,
  settings: SettingsIcon,
  bucket: BucketIcon,
  dollarCircle: DollarCircleIcon,
  logout: LogoutIcon,
  messageDownload: MessageDownloadIcon,
  userAdd: UserAddIcon,
  heart: HeartIcon,
  chatBubble: ChatBubbleIcon,
  video: VideoIcon,
  eye: EyeIcon,
  chevronRight: ChevronRightIcon,
  collection: CollectionIcon,
  fire: FireIcon,
  sun: SunIcon,
  moon: MoonIcon,
  chartBar: ChartBarIcon,
  chevronDown: ChevronDownIcon,
  chevronUp: ChevronUpIcon,
  chevronLeft: ChevronLeftIcon,
  filter: FilterIcon,
  plus: PlusIcon,
  upload: UploadIcon,
  download: DownloadIcon,
  trash: TrashIcon,
  edit: EditIcon,
  sort: SortIcon,
  sortUp: SortUpIcon,
  sortDown: SortDownIcon,
  arrowLeft: ArrowLeftIcon,
  arrowRight: ArrowRightIcon,
  checkMarkCircle: CheckIcon,
  loader: Loader2,
  grid: LayoutGrid,
};
