name: Deploy PR to Staging

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Pr to staging'
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ghcr.io/deveasyclick/tilvio
      REGISTRY: ghcr.io
      KOYEB_APP_NAME: tilvio-staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{env.REGISTRY}}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get short commit SHA
        id: vars
        run: echo "GIT_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:staging-${{ env.GIT_TAG }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:staging

      - name: Install Koyeb CLI
        run: curl -fsSL https://cli.koyeb.com/install.sh | bash

      - name: Login to Koyeb
        run: koyeb login --token ${{ secrets.KOYEB_API_TOKEN }}

      - name: Deploy to Koyeb Staging
        run: |
          koyeb service update ${{ env.KOYEB_APP_NAME }} \
            --image ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:staging-${{ env.GIT_TAG }}

