name: Frontend PR Check
on:
  pull_request:
    branches: [ 'main' ]
    paths:
      - 'frontend/**'


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: frontend

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: '22.x'
        cache: 'npm'
        cache-dependency-path: './frontend/package-lock.json'
    - name: Install dependencies
      run: npm ci
    - name: Lint
      run: npm run lint
    - name: Build
      run: npm run build
